#define LKR_VAS_CUSTOM_SLOTS_COUNT 49

#include "mas_weps.hpp"
#include "caf_weps.hpp"
#include "sc_items.hpp"

#define LKR_VAS_REMOVE_WEAPONS LKR_VAS_CAF_WEPS,LKR_VAS_MAS_WEPS
#define LKR_VAS_REMOVE_MAGAZINES LKR_VAS_CAF_MAGS
#define LKR_VAS_REMOVE_BACKPACKS
#define LKR_VAS_REMOVE_ITEMS LKR_VAS_SC_ITEMS
#define LKR_VAS_REMOVE_GLASSES
